### ISSUE TITLE
Decoding transactions that contain both a V2 and V3 swap

### ISSUE THREAD

**Issue by skt-lance** [Elnaril/uniswap-universal-router-decoder#14] opened 2023-07-18 20:41 UTC
I noticed that for transactions that contain both a V2 and V3 swap, the amount in of the V3 swap seems to be incorrect. 

For example - when decoding this:
0x3593564c000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000064b6e69300000000000000000000000000000000000000000000000000000000000000030a080000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000001e000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000000160000000000000000000000000706abff8bb86ba0b38e66a9043e06a424b9e6bb5000000000000000000000000ffffffffffffffffffffffffffffffffffffffff0000000000000000000000000000000000000000000000000000000064de6c9400000000000000000000000000000000000000000000000000000000000000000000000000000000000000003fc91a3afd70395cd496c647d5a6cc9d4b2b7fad0000000000000000000000000000000000000000000000000000000064b6e69c00000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000041865b9acc924bdd22ae665462d588000e268729143cf3ab8b4ea3521092cf14c8065967ac54a7bff61760e63ac2e17e2e9021f07ed8fd1ad818ee9eab82bfeba11b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000083c234736e8c7ddf51900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002000000000000000000000000706abff8bb86ba0b38e66a9043e06a424b9e6bb5000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc200000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000001800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000213615bb54a241fe300000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002bc02aaa39b223fe8d0a0e5c4f27ead9083c756cc20027106e2a43be0b1d33b726f0ca3b8de60b3482b8b050000000000000000000000000000000000000000000

This decodes to:
(<Function execute(bytes,bytes[],uint256)>, {'commands': b'\n\x08\x00', 'inputs': [(<Function PERMIT2_PERMIT(((address,uint256,uint256,uint256),address,uint256),bytes)>, {'struct': {'details': {'token': '0x706abfF8Bb86bA0b38E66A9043e06a424B9e6BB5', 'amount': 1461501637330902918203684832716283019655932542975, 'expiration': 1692298388, 'nonce': 0}, 'spender': '0x3fC91A3afd70395Cd496C647d5a6CC9D4B2b7FAD', 'sigDeadline': 1689708188}, 'data': b'\x86[\x9a\xcc\x92K\xdd"\xaefTb\xd5\x88\x00\x0e&\x87)\x14<\xf3\xab\x8bN\xa3R\x10\x92\xcf\x14\xc8\x06Yg\xacT\xa7\xbf\xf6\x17`\xe6:\xc2\xe1~.\x90!\xf0~\xd8\xfd\x1a\xd8\x18\xee\x9e\xab\x82\xbf\xeb\xa1\x1b'}), (<Function V2_SWAP_EXACT_IN(address,uint256,uint256,address[],bool)>, {'recipient': '0x0000000000000000000000000000000000000002', 'amountIn': 40777315588000000000000000000, 'amountOutMin': 0, 'path': ['0x706abfF8Bb86bA0b38E66A9043e06a424B9e6BB5', '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'], 'payerIsSender': True}), (<Function V3_SWAP_EXACT_IN(address,uint256,uint256,bytes,bool)>, {'recipient': '0x0000000000000000000000000000000000000001', 'amountIn': **57896044618658097711785492504343953926634992332820282019728792003956564819968**, 'amountOutMin': **38289986341071757283**, 'path': b"\xc0*\xaa9\xb2#\xfe\x8d\n\x0e\\O'\xea\xd9\x08<ul\xc2\x00'\x10n*C\xbe\x0b\x1d3\xb7&\xf0\xca;\x8d\xe6\x0b4\x82\xb8\xb0P", 'payerIsSender': False})], 'deadline': 1689708179})

The amount in and amount outs of the V3 swap are incorrect

This tx is from hash: 0x08689c2b4979df68cd1bb8f6ae675db18a5264a4f14811f5d8fd670192fbc9d7
etherscan: https://etherscan.io/tx/0x08689c2b4979df68cd1bb8f6ae675db18a5264a4f14811f5d8fd670192fbc9d7

**Comment by Elnaril** [comment] 2023-07-19 05:27
Hello and thank you for your interest in this lib! :)

I believe your issue is similar to #10 but with `V2_SWAP_EXACT_IN` and `V3_SWAP_EXACT_IN` interchanged, so you should find there the explanations.
Also, please note the `amountOutMin` is the min amount you wish (including slippage) for the transaction to be valid, not the exact amount you'll get since it's not possible to know it at the moment the transaction is built.

Closing, but feel free to re-open this ticket if you still think the issue is different.

**Closed by Elnaril** 2023-07-19 05:27 UTC

**Comment by skt-lance** [comment] 2023-07-19 12:39
Got it thank you for getting back to me!

**Comment by Elnaril** [comment] 2023-07-19 12:48
Welcome and happy coding! :)
