### ISSUE TITLE
Broken Amounts on a tx with multiple swaps

### ISSUE THREAD

**Issue by tnet-ag** [Elnaril/uniswap-universal-router-decoder#44] opened 2024-03-19 12:33 UTC
I use version 1.1.0

To reproduce try TX

https://etherscan.io/tx/0x4293ec6511d3d9fba510f3638135f5bdf64205b9328c8165190dbd37d191d0a2

The decoded input will be ->

```
{
  'commands': b
  '\x08\x00',
  'inputs': [
    (<Function
    V2_SWAP_EXACT_IN(address,
    uint256,
    uint256,
    address
    [],
    bool)>,
    {
      'recipient': '0x0000000000000000000000000000000000000002',
      'amountIn': 25000000000206173218298377997,
      'amountOutMin': 0,
      'path': [
        '0xaaeE1A9723aaDB7afA2810263653A34bA2C21C7a',
        '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'
      ],
      'payerIsSender': True
    },
    {
      'revert_on_fail': True
    }
    ),
    (<Function
    V3_SWAP_EXACT_IN(address,
    uint256,
    uint256,
    bytes,
    bool)>,
    {
      'recipient': '0x0000000000000000000000000000000000000001',
      'amountIn': 57896044618658097711785492504343953926634992332820282019728792003956564819968,
      'amountOutMin': 15557248383,
      'path': b
      "\xc0*\xaa9\xb2#\xfe\x8d\n\x0e\\O'\xea\xd9\x08<ul\xc2\x00\x01\xf4\xa0\xb8i\x91\xc6!\x8b6\xc1\xd1\x9dJ.\x9e\xb0\xce6\x06\xebH",
      'payerIsSender': False
    },
    {
      'revert_on_fail': True
    }
    )
  ],
  'deadline': 1710842387
}

```

**Comment by Elnaril** [comment] 2024-03-19 12:54
Hello @tnet-ag !
I'm closing this issue as duplicate of #10, #14, #31, but feel free to re-open it with more details if you think the issue is different.
Thank you for your interest in this lib! :)

**Closed by Elnaril** 2024-03-19 12:54 UTC

**Comment by tnet-ag** [comment] 2024-03-19 22:40
@Elnaril 
Thanks for the Links
Very helpful!

Maybe a potential feature for the future to provide a option parameter like "use_finalized_amounts"
In the Background the library fetches then the logs and updates the amounts.

**Comment by Elnaril** [comment] 2024-03-20 07:05
@tnet-ag 
Thank you for your suggestion.
I never added support for logs as they are more related to other contracts (V2 and V3 pools for swaps, token contracts for transfers, WETH for wrap/unwrap, ...) than the UR one. But that could make sense within the context of scope expansion, and if enough users are interested in it.
